- name: "reboot host"
  command: "sleep 2 & shutdown -r now"
  async: 1
  poll: 0
  ignore_errors: true

- name: "wait for host to restart"
  local_action: wait_for host={{ inventory_hostname }} state=started delay=15 timeout=30
  sudo: false

- name: "update cache"
  yum: name=* state=latest update_cache=yes
