- name: "Build container from newly created image"
  docker:
    name: jenkins-agent
    hostname: jenkins-agent
    image: hfoster/jenkins-agent:latest
    pull: missing
    state: started
    ports: 22
