ENV["LC_ALL"] = "en_GB.UTF-8"
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  N = 4
  (1..N).each do |machine_id|
    config.vm.define "machine#{machine_id}" do |machine|
      machine.vm.box = "centos/7"
      machine.vm.hostname = "centos-host-#{machine_id}"

      machine.vm.network :private_network, ip: "192.168.56.20#{machine_id}"

      machine.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 512]
        v.customize ["modifyvm", :id, "--name", "centos-host-#{machine_id}"]
      end

      machine.vm.provision :file, source: "~/.ssh/id_rsa.pub", destination: ".ssh/authorized_keys"
      machine.ssh.forward_agent = true
      if machine_id == N
        machine.vm.provision :ansible do |ansible|
          ansible.verbose = "v"
          ansible.raw_arguments = "--private-key=~/.ssh/id_rsa"
          ansible.playbook = "site.yml"
          ansible.inventory_path = "hosts"
          ansible.sudo = true
          ansible.host_key_checking = false
          ansible.limit = "all"
        end
      end
    end
  end
end
