- name: "Apply eth1 config"
  template: src=ifcfg-eth1.j2 dest=/etc/sysconfig/network-scripts/ifcfg-eth1 mode="0644"

- name: "Apply networking master config"
  template: src=network.j2 dest=/etc/sysconfig/network mode="0644"

- name: "Bounce network"
  service: name=network state=restarted
